<?php
namespace ns;

/**
 * Autogenerated by Disf-CodeGen (0.1.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */    
use Disf\IDL\Common\TypeConverter;
use Disf\IDL\Common\AbstractEnum;


/** 
    * @property int age 
    * @property string name 
    * @property string sex 
*/ 
class People extends \ArrayObject {

    public static $SCHEMA = array( 
        'disfSchemaFormatVersion' => 1003,
        'isUnion' => false,
        'classObject' => People::class,
        'className' => 'ns\People',
        'annotations' => array(),
        'fields' => array(
            "age" => array(
                "fieldId" => 2, 
                "thriftType" => 'I32',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "name" => array(
                "fieldId" => 1, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "sex" => array(
                "fieldId" => 3, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
        ),
    );

    public function __construct($array = null) 
    {
        if (!isset($array)) { 
            parent::__construct(array(), \ArrayObject::ARRAY_AS_PROPS);
            return;
        }

        parent::__construct($array, \ArrayObject::ARRAY_AS_PROPS); 

        if(isset($array["age"])) { 
            $this->setAge($array["age"]);
        }

        if(isset($array["name"])) { 
            $this->setName($array["name"]);
        }

        if(isset($array["sex"])) { 
            $this->setSex($array["sex"]);
        }

    }

    /** 
     * @return int 
    */ 
    public function getAge()/* : int */ {
        return TypeConverter::to_int($this["age"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setAge(/* int */ $val) {
        $this["age"] = TypeConverter::to_int($val);
    }

    /** 
     * @return string 
    */ 
    public function getName()/* : string */ {
        return TypeConverter::to_string($this["name"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setName(/* string */ $val) {
        $this["name"] = TypeConverter::to_string($val);
    }

    /** 
     * @return string 
    */ 
    public function getSex()/* : string */ {
        return TypeConverter::to_string($this["sex"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setSex(/* string */ $val) {
        $this["sex"] = TypeConverter::to_string($val);
    }
}

/* THRIFT IDL
namespace php ns
struct People {
	1: string name;
    2: i32 age;
    3: string sex;
}

*/